# Generated by Django 2.2.24 on 2022-02-25 03:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=255, unique=True)),
                ('pin', models.CharField(blank=True, default='', max_length=10)),
                ('password', models.UUIDField(default=uuid.uuid4)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255, null=True)),
                ('address', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('balance', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
